name: Deploy and Release

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create a new release?"
        required: true
        type: boolean
        default: false
      app:
        description: "App to deploy and release"
        required: true
        type: choice
        options:
          - docs
          - web
      bump_type:
        description: "Version bump type"
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"

jobs:
  deploy-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Your existing deployment steps go here
      # ...

      - name: Call Release Workflow
        if: github.event.inputs.create_release == 'true'
        uses: ./.github/workflows/base-release-app.yml
        with:
          app: ${{ github.event.inputs.app }}
          bump: ${{ github.event.inputs.bump_type }}

      # Continue with any post-release deployment steps
      # ...
